#!/usr/bin/env bash
# Exports the CS2 paint-kit colour wraps that are missing from R2 and uploads them.
# Generated from the game data; each entry maps a game file to its R2 key (cs2-textures/paints/paintkits/...).
#
# Usage (macOS):
#   VPK=~/CS2_PakFiles/game/csgo/pak01_dir.vpk CLI=./Source2Viewer-CLI BUCKET=<your-r2-bucket> scripts/export-paintkit-textures.sh
# Set UPLOAD=0 to only export. MAXSIZE (default 2048) downsizes with macOS `sips` to keep pages fast.
set -euo pipefail
: "${VPK:?set VPK to pak01_dir.vpk}"; : "${CLI:=./Source2Viewer-CLI}"; : "${OUT:=$HOME/cs2_export}"
: "${UPLOAD:=1}"; : "${MAXSIZE:=2048}"
FILES=(
  "limited_time/ak_djiin_albedo_texture_tga_b433cc24"
  "set_spy_tech/ak47_autoexec_camo_albedo_texture_tga_5e17359d"
  "set_overpass_2024/cu_overpass_monster_ak47_albedo_texture_psd_71d2d679"
  "set_arabesque/ak47_jinn_consequence_albedo_texture_psd_8d2aa749"
  "community/community_37/ak47_crane_flight_color_tga_bcbe11b4"
  "set_graphic_design/cu_graphic_overlay_ak47_albedo_texture_psd_f3493794"
  "community/community_33/ak_porcelain_albedo_texture_tga_a86d8420"
  "community/community_35/ak47_explosive_albedo_texture_psd_14b0eb90"
  "community/community_34/ak47_t_bus_albedo_texture_tga_856aaf50"
  "set_overpass_2024/cu_overpass_graf_aug_albedo_texture_psd_265b5289"
  "set_arabesque/aug_lapis_lazuli_color_tga_2fc617cf"
  "set_graphic_design/gs_lilpig_aug_albedo_texture_psd_418d687d"
  "community/community_34/aug_puffer_albedo_texture_psd_8248ca73"
  "set_spy_tech/aug_ghost_signal_albedo_texture_psd_4f0e84d6"
  "set_train_2025/aug_cold_sentinel_albedo_texture_tga_a6f43e67"
  "community/community_36/aug_trigger_discipline_velco_albedo_texture_adjusted_psd_965ce8e"
  "set_spy_tech/awp_black_box_albedo_texture_psd_5754b9a6"
  "community/community_33/awp_tempered_albedo_texture_tga_d56e1436"
  "set_graphic_design/gs_independe_awp_albedo_texture_psd_71f88bf1"
  "set_overpass_2024/cu_overpass_crakow_awp_albedo_texture_psd_19c1752c"
  "community/community_36/awp_ice_coaled_albedo_texture_adjusted_psd_6500e4a0"
  "community/community_35/awp_printstream_albedo_texture_psd_8cd20f19"
  "community/community_37/awp_queens_gambit_albedo_texture_psd_30866ef"
  "set_arabesque/awp_sovereign_flame_albedo_texture_psd_c44789a6"
  "set_spy_tech/cz75_hydraulics_albedo_texture_psd_b5ee0397"
  "set_graphic_design/cu_abstract_white_cz_albedo_texture_psd_54207e48"
  "community/community_34/deagle_calligraff_albedo_texture_tga_ab311676"
  "set_arabesque/deagle_eastern_enigma_blue_albedo_texture_psd_23aeeb92"
  "community/community_37/deagle_firebreathing_albedo_texture_tga_bac044e7"
  "set_graphic_design/cu_glitter_deagle_albedo_texture_psd_25c027da"
  "set_overpass_2024/cu_overpass_aqua_deagle_albedo_texture_psd_e02f0dad"
  "community/community_36/dual_elite_biblical_angel_albedo_texture_adjusted_psd_4ddc5451"
  "community/community_33/dual_berettas_lethal_grin_albedo_texture_tga_1c20d55b"
  "community/community_34/dual_elite_hydro_strike_albedo_texture_tga_61e70d02"
  "set_arabesque/dualies_mystic_conjunction_v3_albedo_texture_psd_e6a5fc59"
  "set_overpass_2024/cu_overpass_baby_dualies_albedo_texture_psd_3327c41a"
  "set_train_2025/gs_train_car_famas_color_png_cdf31553"
  "community/community_35/famas_badtrip_albedo_texture_psd_1543d91a"
  "set_spy_tech/famas_corp_defense_albedo_texture_psd_5cbdd759"
  "set_realism_camo/gs_gamebred_famas_albedo_texture_psd_8fa050cd"
  "set_arabesque/famas_snake_song_albedo_texture_tga_6304537"
  "community/community_37/fiveseven_polymer_dark_color_tga_cb4fd5ea"
  "set_arabesque/fiveseven_desert_seal_albedo_texture_tga_9833df4b"
  "community/community_33/fiveseven_hybrid_albedo_texture_tga_c4332571"
  "community/community_35/galil_control_strike_albedo_texture_psd_a76baaee"
  "community/community_37/galil_galigator_albedo_texture_psd_43e515eb"
  "set_graphic_design/cu_poly_green_galil_albedo_texture_psd_e4a6cfc1"
  "set_realism_camo/gsch_axia_glock_albedo_texture_psd_a85bf403"
  "community/community_33/glock_brick_mondrian_albedo_texture_tga_ce97c013"
  "community/community_37/glock_jdpeek_albedo_texture_psd_9131f8ee"
  "set_spy_tech/glock_ghost_protocol_red_albedo_texture_tga_c2f0f2d0"
  "community/community_34/glock_chomper_albedo_texture_psd_2e5009d2"
  "set_train_2025/glock_train_green_albedo_texture_psd_a0a4ac3"
  "set_arabesque/glock_ifrit_lattice_albedo_texture_psd_4f0e7ee8"
  "community/community_36/glock_mirror_maze_v2_pearl_albedo_texture_adjusted_psd_e0a8bb9"
  "community/community_35/glock_shinobu_albedo_texture_psd_ee909f07"
  "community/community_37/m249_blocks_purple_albedo_texture_psd_3f713bac"
  "community/community_34/m249_hypnosis_albedo_texture_tga_1edf36f5"
  "community/community_33/m4a1s_black_lotus_albedo_texture_tga_2bcd6eb8"
  "community/community_37/m4a1s_electrum_albedo_texture_tga_13627a1f"
  "community/community_36/m4a1s_quick_liquidation_albedo_texture_adjusted_psd_ac64331f"
  "community/community_34/m4a1s_vaporwave_albedo_texture_tga_25d261b9"
  "community/community_35/m4a4_green_camo_albedo_texture_psd_8598e983"
  "set_spy_tech/m4a4_black_side_matte_albedo_texture_psd_e00dae13"
  "community/community_33/m4a4_snakebite_albedo_texture_tga_c73f8491"
  "set_arabesque/m4a4_falak_albedo_texture_psd_843c5d54"
  "community/community_36/m4a4_skrrrt_green_albedo_texture_adjusted_psd_6b3ef59f"
  "set_train_2025/m4a4_train_hell_albedo_texture_psd_7ab39162"
  "community/community_34/m4a4_fusion_albedo_texture_psd_6b2374b0"
  "community/community_37/m4a4_zubastick_bw_albedo_texture_psd_b715c38e"
  "community/community_36/mac10_kamicatze_albedo_texture_adjusted_psd_fccae04a"
  "set_train_2025/mac10_train_crash_albedo_texture_psd_9f391f71"
  "community/community_33/mac10_illusion_albedo_texture_tga_7f186e7d"
  "set_overpass_2024/cu_overpass_squeak_mac10_albedo_texture_psd_1ba98f6d"
  "community/community_34/mac10_ozaki_albedo_texture_psd_d744565f"
  "set_spy_tech/mac10_video_cam_albedo_texture_psd_ebca90f3"
  "community/community_36/mag7_circle_copper_albedo_texture_adjusted_psd_327a434d"
  "community/community_35/mag7_ammo_box_albedo_texture_tga_9256b9b2"
  "community/community_36/mp5sd_chrome_albedo_texture_adjusted_psd_bd8ff271"
  "community/community_34/mp5_statics_blue_albedo_texture_psd_340eedc2"
  "set_graphic_design/gs_constellation_dark_mp7_albedo_texture_psd_f50fee3c"
  "set_spy_tech/mp7_binary_green_albedo_texture_tga_ae71b42e"
  "community/community_33/mp7_just_smile_albedo_texture_tga_218011a7"
  "community/community_36/mp7_smoking_kills_v2_albedo_texture_adjusted_psd_91d7943b"
  "set_realism_camo/gs_arctic_mp9_albedo_texture_png_287f467e"
  "community/community_36/mp9_vinyl_albedo_texture_tga_b04aad31"
  "set_arabesque/mp9_dune_asp_albedo_texture_tga_5699388e"
  "set_train_2025/cu_mp9_latte_color_tga_eb5f5c7e"
  "community/community_35/mp9_nexus_albedo_texture_tga_f857ff3"
  "set_spy_tech/mp9_prototype_extended_albedo_texture_psd_e99ce2dc"
  "community/community_37/mp9_urban_sovereign_albedo_texture_psd_a1776cc"
  "set_overpass_2024/cu_overpass_graf_negev_albedo_texture_psd_ed5c2f75"
  "community/community_33/nova_drakkar_albedo_texture_tga_a14bf32e"
  "set_arabesque/nova_morning_sun_albedo_texture_tga_2a9a5401"
  "community/community_36/nova_ocular_albedo_texture_adjusted_psd_476c7c26"
  "community/community_35/nova_rising_sun_albedo_texture_tga_66b5c8e8"
  "set_spy_tech/nova_smart_albedo_texture_tga_89615cbd"
  "set_overpass_2024/cu_overpass_wurst_nova_albedo_texture_psd_807b31b7"
  "set_realism_camo/gs_ripple_nova_albedo_texture_psd_f9260807"
  "community/community_36/p2000_deep_red_albedo_texture_tga_f2668bb3"
  "community/community_35/p2k_fractal_albedo_texture_tga_6806e48f"
  "community/community_36/p250_bullfrog_albedo_texture_tga_4d93e6a3"
  "community/community_34/p250_impact_albedo_texture_tga_897967dc"
  "community/community_37/p250_kintsugi_albedo_texture_psd_1bb4151a"
  "set_arabesque/p250_lotus_imprint_glitter_purple_albedo_texture_psd_d3314e32"
  "set_graphic_design/cu_poly_violet_p90_albedo_texture_psd_18cc506c"
  "community/community_37/p90_deathgaze_albedo_texture_psd_b40ea6f9"
  "community/community_34/p90_randy_rush_albedo_texture_tga_a65cdceb"
  "set_train_2025/p90_steelcraft_albedo_texture_tga_3492a611"
  "community/community_35/p90_boost_blue_albedo_texture_psd_2061394"
  "community/community_37/bizon_rmx_albedo_texture_psd_50a4acac"
  "set_arabesque/bizon_traitor_albedo_texture_psd_872527a7"
  "community/community_34/r8_roses_and_guns_albedo_texture_psd_2fbb729a"
  "community/community_33/sawedoff_gamer_albedo_texture_tga_8262d35a"
  "community/community_37/sawedoff_fusion_albedo_texture_psd_1c3d44"
  "set_arabesque/sawedoff_lunar_wyrm_albedo_texture_psd_d3015451"
  "set_spy_tech/scar_arctic_camo_panels_albedo_texture_psd_d01fecd4"
  "community/community_36/scar_refraction_v4_albedo_texture_adjusted_psd_7260dd22"
  "community/community_34/scar20_fury_topo_albedo_texture_psd_5a4e43b1"
  "set_graphic_design/cu_chevron_scar20_albedo_texture_psd_a3387b61"
  "set_graphic_design/gs_happy_red_sg556_albedo_texture_psd_2f886704"
  "community/community_33/ssg08_dezastre_albedo_texture_tga_b441e3c7"
  "community/community_35/ssg08_brutalist_albedo_texture_tga_6bd3b93e"
  "community/community_34/ssg08_transit_white_albedo_texture_tga_e33133c7"
  "set_realism_camo/gsch_zeno_ssg08_albedo_texture_psd_4872a4c5"
  "set_spy_tech/tec9_perimeter_urban_albedo_texture_tga_f8953a6"
  "community/community_33/tec9_junkyard_engineering_albedo_texture_tga_2c0168f8"
  "set_arabesque/tec9_sultan_albedo_texture_tga_e30d567e"
  "community/community_36/ump45_illumina_v2_albedo_texture_adjusted_psd_16927d00"
  "set_realism_camo/gsch_sport_ump45_albedo_texture_png_d19d10a0"
  "community/community_37/ump_fragment_albedo_texture_psd_4b9af607"
  "community/community_35/ump45_old_cartoon_albedo_texture_psd_30a9d05d"
  "set_train_2025/ump_transit_albedo_texture_tga_10ede841"
  "community/community_33/ump45_assembled_engine_albedo_texture_tga_dff49436"
  "community/community_34/ump45_neo_noir_albedo_texture_psd_efefd77a"
  "community/community_34/usp_field_snake_albedo_texture_psd_5fbea817"
  "set_realism_camo/gsch_bright_camo_usp_albedo_texture_psd_c47cc26c"
  "community/community_33/usps_doggy_albedo_texture_tga_a38bac84"
  "community/community_35/usps_bruteforce_green_albedo_texture_psd_cdc37f1"
  "community/community_37/usps_silent_boy_albedo_texture_psd_31d8759f"
  "set_spy_tech/usps_spiral_glitch_iridescent_albedo_texture_tga_4b89ca0f"
  "set_spy_tech/xm1014_black_site_albedo_texture_psd_bdef7d39"
  "community/community_33/xm1014_irezumi_albedo_texture_tga_7f067488"
  "community/community_35/xm1014_mockingbird_albedo_texture_psd_cfca4ba9"
  "set_overpass_2024/cu_overpass_monsters_xm_albedo_texture_psd_45998c7a"
  "set_train_2025/xm1014_freight_albedo_texture_tga_bfc00009"
  "set_train_2025/zeus_standard_issue_albedo_texture_psd_86d569cf"
  "set_overpass_2024/cu_overpass_dragon_zeus_albedo_texture_psd_2a1195d7"
  "community/community_33/zeus_thunder_god_albedo_texture_tga_9e2fbb81"
  "community/community_35/zeus_tosai_albedo_texture_tga_ab8700eb"
)

mkdir -p "$OUT"
# export in chunks so the --vpk_filepath filter stays short
for ((i=0; i<${#FILES[@]}; i+=15)); do
  filter=""; for p in "${FILES[@]:i:15}"; do filter+="items/assets/paintkits/${p}.vtex_c,"; done
  "$CLI" -i "$VPK" -o "$OUT" -d -e vtex_c -f "${filter%,}"
done

for p in "${FILES[@]}"; do
  src="$OUT/items/assets/paintkits/${p}.png"
  [ -f "$src" ] || { echo "missing export: $src" >&2; continue; }
  if command -v sips >/dev/null; then sips -Z "$MAXSIZE" "$src" >/dev/null; fi
  if [ "$UPLOAD" = 1 ]; then
    npx wrangler r2 object put "$BUCKET/cs2-textures/paints/paintkits/${p}.png" --file "$src" --content-type image/png --remote
  fi
done
echo "done: ${#FILES[@]} textures"
